name: Paul'Blog
description: 纪录Paul的生活
meta_description: "2015，新的开始，新的生活"

markdown: kramdown
highlighter: rouge
permalink: /:title.html
logo: false
comments: true
paginate: 15
baseurl: /p
domain_name: 'http://paulreina.com'
url: 'http://paulreina.com/p'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://paulreina.github.io/'
author:         'Paul chan'
