name: Paul'Blog
description: 纪录Paul的生活
meta_description: "2015，新的开始，新的生活"

markdown: redcarpet
highlighter: pygments
permalink: /:title.html
logo: false
paginate: 15
baseurl: /p
domain_name: 'http://paulreina.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://paulreina.com/p/'
author:         'Paul chan'
